server:
    port: 7777
spring:
    application:
        name: springboot-admin-server
    # 设置登录密码
    security:
        user:
            name: admin
            password: 123456

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        # 注意：include: ["health", "info"] 但已无效了，请修改
#        include: health,info